language: node_js
node_js:
- "8"

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm run build && npm publish"
  skip_cleanup: true
  on:
    tags: true

deploy:
  provider: script
  script: "npm run deploy-storybook -- --ci --host-token-env-variable=GITHUB_TOKEN"
  skip-cleanup: true
  keep-history: true
  on:
    branch: master

notifications:
  email:
    recipients:
    - wizcheng@gmail.com
    on_success: change
    on_failure: always
