language: node_js
node_js:
- "8"

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm build && npm publish"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - wizcheng@gmail.com
    on_success: change
    on_failure: always
